# workflow:
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
#    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
#      when: never
#    - if: '$CI_COMMIT_BRANCH'

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build
  - test

build_linux:
  image: ros:noetic-perception-focal
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  stage: build
  tags:
    - ros
  script:
    - rm -rf build devel
    - catkin_make
    - roscore &
    - roscore_pid=$!
    - catkin_make run_tests
    - kill $roscore_pid

